version: 2
before:
  hooks:
    - go generate
    - go mod download

builds:
  - id: pathvector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

changelog:
  use: github
  sort: desc
  filters:
    exclude:
      - '^test:'

nfpms:
  - id: pathvector
    package_name: pathvector
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Agustin Lorenzo
    homepage: https://github.com/AgustinLorenzo/pathvector
    maintainer: Agustin Lorenzo <agustin.lorenzo@thinco.es>
    description: Community-maintained fork of Pathvector, a declarative edge routing platform that automates route optimization and control plane configuration with secure and repeatable routing policy.
    license: MIT
    section: utils
    priority: extra
    ids:
      - pathvector

    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - pathvector
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/agustinlorenzo/

